In [2]:
import numpy as np
import pandas as pd

In [23]:
list_1d = [1,2,4,5,6,7]
list_2d = [[1,2,3], [2,2,3]]

In [24]:
np_array_1d = np.array(list_1d)
np_array_2d = np.array(list_2d)
print(np_array_1d, '\n' ,np_array_2d)

[1 2 4 5 6 7] 
 [[1 2 3]
 [2 2 3]]


Performing Mathematical operations on np Array

In [25]:
print(' Addition',np_array_1d + 2, '\n','Division', np_array_2d / 2, '\n Exponential ', np_array_1d ** 2)

 Addition [3 4 6 7 8 9] 
 Division [[0.5 1.  1.5]
 [1.  1.  1.5]] 
 Exponential  [ 1  4 16 25 36 49]


Looping through np.array

In [26]:
addition = np_array_1d + 3
for num in addition:
    print(num)

4
5
7
8
9
10


`A pandas Series is very similar to a one-dimensional NumPy array, but it has additional functionality that allows values in the Series to be indexed using labels. A NumPy array does not have the flexibility to do this. This labeling is useful when you are storing pieces of data that have other data associated with them. Say you want to store the ages of students in an online course to eventually figure out the average student age. If stored in a NumPy array, you could only access these ages with the internal ndarray indices 0,1,2.... With a Series object, the indices of values are set to 0,1,2... by default, but you can customize the indices to be other values such as student names so an age can be accessed using a name.`

In [27]:
ages = np.array([13,25,19])
series1 = pd.Series(ages)
print(series1)

0    13
1    25
2    19
dtype: int64


In [28]:
ages = np.array([13,25,19])
series1 = pd.Series(ages,index=['Emma', 'Swetha', 'Serajh'])
print(series1)

Emma      13
Swetha    25
Serajh    19
dtype: int64


### Understanding Pandas DataFrame

A **DataFrame** in pandas is like a matrix with rows and columns. Here's a simple explanation:

- **Rows and Columns**: 
  - Rows and columns can be labeled with **integers** or **strings**.
- **Data Types**:
  - A DataFrame can hold different types of data (e.g., numbers, strings) in different columns.
  - However, within a column, all values must have the **same data type**.
  - Each column is essentially a **Series**.
- **Column Length**:
  - All columns must have the **same number of rows**.

### Creating a DataFrame

You can create a DataFrame in various ways:
- From a **CSV file**
- From a **SQL query**
- Using a **Python list** or a **dictionary**

In [4]:

data = [
    [1, 'Alice', 25],
    [2, 'Bob', 30],
    [3, 'Charlie', 35]
]

# Define column names
columns = ['ID', 'Name', 'Age']

# Create the DataFrame
df = pd.DataFrame(data, columns=columns)

print(df)

   ID     Name  Age
0   1    Alice   25
1   2      Bob   30
2   3  Charlie   35


# np.zeros , np.ones
* np.zeros((ROW, COLUMN)) -
    - It creates numpy Array, which consist zeros defined in tuple, It takes 2 values in tuple, number of rows and number of column
* np.ones((ROW, COLUMN)) -
    - It is similar to np.zeros, but instead of zeros it creates one.

If Column is not passed or if a single number is passed then it is consider as 1D array. else length of tuple = that Demission array.


In [13]:
zeros = np.zeros((2, 1))
ones = np.ones((1,3))
print("Zeros -> ",  zeros, '\n ones ->', ones)

Zeros ->  [0. 0.] 
 ones -> [[1. 1. 1.]]


In [14]:
np.zeros(4)

array([0., 0., 0., 0.])

# np.arange, np.linspace
- np.arange(start, stop, step(Opt)) -
    *	Generates an array with evenly spaced values within a range.
    *	Use case: Like range() but returns a NumPy array.
- np.linespace(start, stop, step(Opt)) -
    *   Creates an array with a specified number of equally spaced values between two numbers.
	*	Use case: Great for plotting or sampling.

In [15]:
np.arange(0, 10, 2)  # Start=0, Stop=10 (exclusive), Step=2

array([0, 2, 4, 6, 8])

In [16]:
np.linspace(0, 1, 5)  # Start=0, Stop=1, 5 values

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

# Indexing, Slicing, Reshaping
* Indexing:
    - 0 based Indexing
* Slicing:
    - Slicing is used to extract the sub-arrays.
    -  Extract subarrays using the format [ start:stop:step ].
* Reshaping:
    - Change the shape of an array without altering data.

In [17]:
arr = np.array([10, 20, 30, 40])
print(arr[0])

10


In [19]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr[0,1])

2


# numpy Random Numbers

Below Generates 5 random numbers between 0 to 1

In [21]:
np.random.rand(5) 

array([0.17445438, 0.48428304, 0.91697557, 0.06933083, 0.37708005])

Standard normal distribution (mean=0, std=1).

In [25]:
np.random.randn(3)

array([ 0.10039049,  0.97702494, -2.15495564])

Random Integers between start and end given 

In [29]:
np.random.randint(1, 10, size=(5,))

array([5, 7, 7, 5, 9])

# NumPy Built-in Functions for Statistical Analysis

NumPy provides various built-in functions for statistical analysis, ranging from basic statistical measures to advanced operations like correlation and covariance.

## **1. Basic Statistical Measures**

| **Function**   | **Description**                                 |
|-----------------|-------------------------------------------------|
| `np.mean()`     | Calculates the mean (average) of the array.    |
| `np.median()`   | Calculates the median value of the array.      |
| `np.std()`      | Calculates the standard deviation.             |
| `np.var()`      | Calculates the variance.                       |
| `np.sum()`      | Computes the sum of all elements in the array. |
| `np.prod()`     | Computes the product of all elements in the array. |
| `np.min()`      | Finds the minimum value.                       |
| `np.max()`      | Finds the maximum value.                       |
| `np.ptp()`      | Calculates the range (max - min) of values.    |


Mean

In [50]:
arr = np.arange(1, 6)

In [51]:
mean = np.mean(arr)
median = np.median(arr)
std = np.std(arr)
var = np.var(arr)

print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std)
print("Variance:", var)

Mean: 3.0
Median: 3.0
Standard Deviation: 1.4142135623730951
Variance: 2.0


In [52]:
sum_arr = np.sum(arr)
prod_arr = np.prod(arr)
print("Sum of element", sum_arr)
print("Product of element", prod_arr)

Sum of element 15
Product of element 120


In [53]:
min_num = np.min(arr)
max_num = np.max(arr)
ptp = np.ptp(arr)

print("Minimum number:", min_num)
print("Maximum number:", max_num)
print("Peak-to-peak value:", ptp)


Minimum number: 1
Maximum number: 5
Peak-to-peak value: 4


In [54]:
arr = np.random.randint(1, 10, size=(2, 3))

# Percentile and Quantile

Percentile Computes the q-th percentile of the data.  
A percentile is a value that indicates the percentage of data points in a dataset that are below it. Percentiles divide the dataset into 100 equal parts.

In [65]:
arr = np.random.randint(1, 100, size=(11,))

In [66]:
arr.sort()
arr

array([13, 16, 21, 29, 46, 52, 53, 62, 66, 67, 76])

In [67]:
# 25th percentile
p25 = np.percentile(arr, 25)
print("25th percentile:", p25)  
# 50th percentile  
p50 = np.percentile(arr, 50)
print("50th percentile:", p50)  
# 90th percentile
p90 = np.percentile(arr, 90)
print("90th percentile:", p90)

25th percentile: 25.0
50th percentile: 52.0
75th percentile: 67.0


Quantile is similar to percentile but it uses fractions instead of percentage

In [68]:
q22 = np.quantile(arr, 0.22)
print("22nd percentile:", q22)

q37 = np.quantile(arr, 0.37)
print("37th percentile:", q37)

q79 = np.quantile(arr, 0.79)
print("79th percentile:", q79)

22nd percentile: 22.6
37th percentile: 40.900000000000006
79th percentile: 65.6


# Broadcast and Vectorized

**Vectorized operations** are operations that are applied to entire arrays (or slices of arrays) at once, rather than using explicit loops. This is faster and more efficient because NumPy is optimized for such operations.

In [73]:
array1 = np.array([1, 2, 3])  # Shape (3)
array2 = np.array([10, 20, 30])  # Shape (3,)

In [75]:
array1 + array2 # Vectorized operation

array([11, 22, 33])

# Broadcasting

Broadcasting is a powerful feature in NumPy that allows you to perform operations on arrays of different shapes. NumPy automatically "broadcasts" the smaller array across the larger one so they have compatible shapes.

Rules of Broadcasting:

1. Align shapes from the right: Compare the shapes of the two arrays from the rightmost dimension.
2. Dimensions must match or be 1: For each dimension, the sizes must either be equal, or one of them must be 1.
3. Missing dimensions are treated as 1: If one array has fewer dimensions, it’s padded with ones on the left.

In [78]:
# Example 1: Broadcasting a scalar to an array
array1 = np.array([1, 2, 3, 4, 5]);

array1 + 5

array([ 6,  7,  8,  9, 10])

In [81]:
# Example 2: Broadcasting arrays of different shapes
array2 = np.array([[11, 22, 33, 44, 55], [10, 20, 30, 40, 50]]);

array1 + array2

array([[12, 24, 36, 48, 60],
       [11, 22, 33, 44, 55]])

# Vectorized Operations
Vectorized operations allow you to perform element-wise operations on entire arrays (or slices) without writing explicit loops. Instead of iterating over each element manually, NumPy applies the operation to all elements at once, leveraging optimized, low-level code (written in C) under the hood. This makes them much faster than Python loops.

1. Operations are applied to every element.
2. We don't required multiple loops for applying operations for every element.
3. Works with Scalars and Arrays

Vectorized operations are performed on similar shape arrays.
If Shapes are different, With help of the Broadcasting Vectorized operations are performed.

In [84]:
array1 = np.random.randint(1, 10, size=(2, 5))
array2 = np.random.randint(1, 10, size=(2, 5))
array1, array2

(array([[1, 2, 1, 6, 7],
        [9, 3, 1, 9, 5]]),
 array([[5, 8, 8, 7, 8],
        [7, 6, 3, 1, 3]]))

In [85]:
array1 + array2 # Vectorized operation are applied here

array([[ 6, 10,  9, 13, 15],
       [16,  9,  4, 10,  8]])

In [86]:
np.sin(array1)

array([[ 0.84147098,  0.90929743,  0.84147098, -0.2794155 ,  0.6569866 ],
       [ 0.41211849,  0.14112001,  0.84147098,  0.41211849, -0.95892427]])

In [91]:
array2 < array1 % 2
#  array1 % 2 is converting to Int instead of float


array([[False, False, False, False, False],
       [False, False, False, False, False]])

In [94]:
# Vectorized operation enabled by broadcasting
matrix = np.array([[1, 2], [3, 4]])  # Shape: (2, 2)
vector = np.array([10, 20])          # Shape: (2,)

matrix + vector  
# Broadcasting stretches `vector` to [[10, 20], [10, 20]]
# Result: [[11, 22], [13, 24]]

array([[11, 22],
       [13, 24]])

In [96]:
np.reshape(vector, (2,2 ))

ValueError: cannot reshape array of size 2 into shape (2,2)